x-common-application-variables: &common-application-variables
  DEBUG: "True"
  DJANGO_SETTINGS_MODULE: request_a_govuk_domain.settings
  DATABASE_URL: postgresql://govuk_domain:govuk_domain@postgres:5432/govuk_domain  # pragma: allowlist secret


x-api-base: &api-base
  platform: linux/amd64
  build:
    context: .
    args:
      POETRY_ARGS: "--no-root --no-ansi"
  volumes:
    - .:/srv/request_a_govuk_domain

services:

  web:
    platform: linux/amd64
    build:
      context: .
      args:
        POETRY_ARGS: "--no-root --no-ansi"
    volumes:
      - ./request_a_govuk_domain:/srv/request_a_govuk_domain/request_a_govuk_domain
      - govuk_domain_home:/home/govuk_domain
    ports:
      - "8000:8000"
    #Added the reload flag so the application will be reloaded when the source is modified.
    entrypoint: [ "/usr/local/bin/gunicorn", "request_a_govuk_domain.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120", "--access-logfile", "-", "--reload" ]
    environment:
      <<: *common-application-variables
    depends_on:
      postgres:
        condition: service_started

  postgres:
    platform: linux/amd64
    image: postgres
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: govuk_domain
      POSTGRES_PASSWORD: govuk_domain  # pragma: allowlist secret
      POSTGRES_DB: govuk_domain
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  init:
    <<: *api-base
    restart: 'no'
    environment:
      <<: *common-application-variables
    command: [ "sh", "-c", "python manage.py migrate --noinput && python manage.py loaddata ./seed/reviewer_group.json ./seed/users.json ./seed/request.json" ]
    depends_on:
      - postgres


volumes:
  postgres-data: { }
  govuk_domain_home: { }
