x-common-application-variables: &common-application-variables
  DEBUG: "True"
  SECRET_KEY: "Unneeded"  # pragma: allowlist secret
  DJANGO_SETTINGS_MODULE: request_a_govuk_domain.settings
  DATABASE_URL: postgresql://govuk_domain:govuk_domain@postgres:5432/govuk_domain  # pragma: allowlist secret


x-api-base: &api-base
  platform: linux/amd64
  build:
    context: .
    args:
      POETRY_ARGS: "--no-root --no-ansi"


services:

  web:
    platform: linux/amd64
    <<: *api-base
    ports:
      - "8010:8000"
    #Added the reload flag so the application will be reloaded when the source is modified.
    entrypoint: [ "/usr/local/bin/gunicorn", "request_a_govuk_domain.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120", "--access-logfile", "-", "--reload" ]
    environment:
      <<: *common-application-variables
    volumes:
      - .:/app
      - govuk_domain_home:/home/govuk_domain
    depends_on:
      postgres:
          condition: service_healthy
      init:
        condition: service_completed_successfully
      clamav:
        condition: service_started
    networks:
      - clam-net

  postgres:
    platform: linux/amd64
    image: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: govuk_domain
      POSTGRES_PASSWORD: govuk_domain  # pragma: allowlist secret
      POSTGRES_DB: govuk_domain
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clam-net

  clamav:
    platform: linux/amd64
    image: clamav/clamav:latest
    restart: unless-stopped
    ports:
      - "3310:3310"
    networks:
      - clam-net

  init:
    <<: *api-base
    restart: 'no'
    environment:
      <<: *common-application-variables
    command: [ "sh", "/app/local-init.sh" ]
    volumes:
      - .:/app
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      - clam-net


volumes:
  postgres-data: { }
  govuk_domain_home: { }

networks:
  clam-net:
