# Generated by Django 4.2.11 on 2024-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
