name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_DB: govuk_domain
          POSTGRES_USER: govuk_domain
          POSTGRES_PASSWORD: govuk_domain
        ports:
          - "5432:5432"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Install required system packages
      run: |
        sudo apt-get update &&
        sudo apt-get -y install libcurl4-nss-dev curl git make build-essential libssl-dev zlib1g-dev libbz2-dev \
        libreadline-dev libsqlite3-dev wget ca-certificates libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
        libffi-dev liblzma-dev mecab-ipadic-utf8 unzip clamav clamav-daemon clamav-freshclam --fix-missing
    # When we deploy in prod we will have a clamav installed and we will do below to update the clamav database
    # and expose the clamav-deamon on tcp host and port with "clamav" as alias.
    - name: Run freshclam to update virus database
      run: |
        sudo /etc/init.d/clamav-freshclam stop
        sudo freshclam
        sudo /etc/init.d/clamav-freshclam start
        sudo systemctl stop clamav-daemon.service
        sudo sed -i -e $'$a\\\TCPAddr 127.0.0.1' /etc/clamav/clamd.conf
        sudo sed -i -e $'$a\\\nTCPSocket 3310' /etc/clamav/clamd.conf
        sudo sed -i '/127.0.0.1 localhost/ s/$/ clamav/' /etc/hosts
        sudo systemctl start clamav-daemon.service
        sudo cat /etc/hosts
    - name: Install pyenv and Python
      run: |
        curl https://pyenv.run | bash && \
        export PYENV_ROOT="$HOME/.pyenv" && \
        [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH" && \
        eval "$(pyenv init -)" && \
        pyenv update && \
        pyenv install 3.10.11 && \
        pyenv global 3.10.11 && \
        pyenv rehash
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade poetry pre-commit
        poetry install --no-root
    - name: Run linters
      run: |
        pre-commit run --all
    - name: Init server
      env:
        SECRET_KEY: blah
        DATABASE_URL: postgresql://govuk_domain:govuk_domain@localhost:5432/govuk_domain
        DOMAIN_NAME: http://localhost:8010
      run: |
        poetry run ./manage.py collectstatic --noinput
        poetry run ./manage.py migrate --noinput
        poetry run ./manage.py create_reviewer_group
        poetry run ./manage.py loaddata ./seed/users.json
        poetry run ./manage.py create_sample_data

    - name: Cypress
      uses: cypress-io/github-action@v6
      env:
        SECRET_KEY: blah
        DATABASE_URL: postgresql://govuk_domain:govuk_domain@localhost:5432/govuk_domain
        DEBUG: True
        DOMAIN_NAME: http://localhost:8010
      with:
        start: |
          /home/runner/work/domains-register-a-govuk-domain/domains-register-a-govuk-domain/.github/workflows/start-server.sh
    - name: Run Unit Tests
      env:
        DATABASE_URL: postgresql://govuk_domain:govuk_domain@localhost:5432/govuk_domain
      run: |
        SECRET_KEY=unneeded DOMAIN_NAME=http://localhost:8010 poetry run python manage.py test -v 2
